### ISSUE TITLE
4:1: Error: A library can't opt out of null safety by default, when using sound null safety. // @dart=2.0

### ISSUE THREAD

**Issue by ADLsourceCode** [influxdata/influxdb-client-dart#13]
Give me the below error while building the app:-

`package/influxdb-client/lib/model/write_precision.dart:4:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.0
^^^^^^^^^^^^
`

this error comes in many files on the package... Kindly guide me 

@pauldix  @brettbuddin @mkmik @stuartcarnie @rockstar

**Comment by bednar** [comment]
Hi @ADLsourceCode,

thanks for using our client.

Which version of Dart do you use?

Regards

**Comment by bednar** [comment]
@ADLsourceCode thanks for quick response.

How do you build your project? Do you use configured web compilers (https://github.com/dart-lang/build/blob/master/build_web_compilers/README.md#configuring-the-sound-null-safety-mode)?
