### ISSUE TITLE
Will this package works for Web Browser?

### ISSUE THREAD

**Issue by YugalAnvation** [influxdata/influxdb-client-dart#135]
**Proposal:**
on which http should I host to connect for InfluxDBClient.

**Current behavior:**
This app is linked to the debug service: ws://127.0.0.1:62792/84DCuPDXMfw=/ws
Debug service listening on ws://127.0.0.1:62792/84DCuPDXMfw=/ws
Connecting to VM Service at ws://127.0.0.1:62792/84DCuPDXMfw=/ws
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The webOnlySetPluginHandler API is deprecated and will be removed in a future release. Please use `setPluginHandler` from `dart:ui_web` instead.

**Use case:**
We want to make a dashboard view for FlutterWeb?
```[tasklist]
### Tasks
- [ ] I was trying to implement to FlutterWeb but unable to acheive can anyone give an example at least?
```

**Comment by bednar** [comment]
Hi @YugalAnvation,

Thank you for using our package. The library is designed to be used in a web environment. Could you provide more details about the connection issues you're experiencing?

Best regards
