### ISSUE TITLE
Unhandled Exception: InfluxDBException: statusCode = 400, code = invalid, message = failed to decode request body: unsupported Content-Type header value

### ISSUE THREAD

**Issue by ADLsourceCode** [influxdata/influxdb-client-dart#14]
```
var queryService = client.getQueryService();

                var recordStream = await queryService.query('''
                from(bucket: "pasiv")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "AAPL")
  |> filter(fn: (r) => r["_field"] == "price")
  |> aggregateWindow(every: 24h, fn: last, createEmpty: false)
  |> yield(name: "last")
                ''');

                var count = 0;
                await recordStream.forEach((record) {
                  print(record.entries.toList().toString());
                  // print(
                  //     'record: ${count++} ${record['_time']}: ${record['host']} ${record['cpu']} ${record['_value']}');
                });

   client = InfluxDBClient(
        url: 'https://us-east-1-1.aws.cloud2.influxdata.com',
        token: 'TOKEN',
        org: 'jenish',

        bucket: 'pasiv',
        debug: true);

```

Below is the error I get :-

````
 >> contentLength: 476
I/flutter (30265): << status: 400 - contentLength: 99
I/flutter (30265): << headers: {connection: keep-alive, trace-id: 15993b584670a3a2, date: Fri, 08 Oct 2021 14:47:57 GMT, trace-sampled: false, vary: Accept-Encoding, strict-transport-security: max-age=15724800; includeSubDomains, content-length: 99, content-type: application/json; charset=utf-8, x-platform-error-code: invalid, x-influxdb-build: Cloud}


[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: InfluxDBException: statusCode = 400, code = invalid, message = failed to decode request body: unsupported Content-Type header value
```

`

@pauldix  @brettbuddin @mkmik @stuartcarnie @rockstar

**Comment by bednar** [comment]
Hi @ADLsourceCode,

thanks for using our client. 

I have prepared a fixed version within #15.

If you would like to use the fixed version of the client before release into `pub.dev`, then you can import the library by:

```
dependencies:
  influxdb_client:
    git:
      url: git@github.com:influxdata/influxdb-client-dart.git
      ref: fix/missing_content_type
```

- https://dart.dev/tools/pub/dependencies#git-packages

Regards

**Comment by ADLsourceCode** [comment]
Getting the below 

Git error. Command: `git rev-list --max-count=1 fix/missing_content_type`
stdout: 
stderr: fatal: ambiguous argument 'fix/missing_content_type': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128

@bednar

**Comment by bednar** [comment]
The PR is already merged into main branch. You have to use `main` instead
of  `fix/missing_content_type`.

**Comment by bednar** [comment]
The error is caused by your query: `|> range(start: v.timeRangeStart, stop: v.timeRangeStop)`. You have to add correct values for `start` and `stop`.

**Comment by ADLsourceCode** [comment]
i tried adding start:0, still it comes.... any example for start and stop you can provide for now to test the query

**Comment by ADLsourceCode** [comment]
I get the below data:-
` [, result, table, _start, _stop, _time, _value, _field, _measurement]
I/flutter (14410): [, last, 0, 2021-10-13T11:44:40.561897499Z, 2021-10-18T11:44:40.561897499Z, 2021-10-14T00:00:00Z, 140.4018, price, AAPL]
I/flutter (14410): [, last, 0, 2021-10-13T11:44:40.561897499Z, 2021-10-18T11:44:40.561897499Z, 2021-10-15T00:00:00Z, 140.91, price, AAPL]`

How can i continuously stream data to get the latest data everytime..


@bednar
