### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by ConnorDykes** [influxdata/influxdb-client-dart#146]
**Describe the bug**
Im not sure what changed but I am all of the sudden getting unauthorized statusCode 401 when I try to write to the DB

**To Reproduce**
1. step1
2. ...

**Expected behavior**

**Specifications:**
 - Client Version: 
 - InfluxDB Version: 2.9.0
 - Platform: iOS and android 

**Additional context**

**Comment by bednar** [comment]
Hi @ConnorDykes,

Thank you for using our client and for reaching out with your issue.

The "unauthorized - 401" error indicates there's a problem with authentication. To help you more effectively, I need a bit more context about the issue:

1. **Frequency of the Error**: Is this an intermittent problem, or does it occur every time you try to connect?
2. **Environment**: Are you using the cloud version of InfluxDB, or is your instance hosted on-premises? If it's hosted, is there a proxy involved?
3. **Authentication Details**: How are you currently handling authentication in the client? For example, are you using a token, and if so, could you confirm that it is still valid and has the necessary permissions?

Please provide this additional information at your earliest convenience so we can pinpoint the source of the issue and assist you in resolving it.

Best Regards
