### ISSUE TITLE
Support for intl 0.19.0 to be able to use the latest dart version

### ISSUE THREAD

**Issue by ConnorDykes** [influxdata/influxdb-client-dart#150]
**Proposal:**
Short summary of the feature.

**Current behavior:**
Describe what currently happens.

**Desired behavior:**
Describe what you want.

**Alternatives considered:**
Describe other solutions or features you considered.

**Use case:**
Why is this important (helps with prioritizing requests)?

**Comment by bednar** [comment]
There is also abandoned PR for this https://github.com/influxdata/influxdb-client-dart/pull/149
