### ISSUE TITLE
Web client error: String.fromEnvironment can only be used as a const constructor

### ISSUE THREAD

**Issue by BSBoatia** [influxdata/influxdb-client-dart#24]
Thank you for adding web support to the client. Very happy about it! would be great if you could have a look at the issue, which is assume is a bug somewhere inside the client.

**Describe the bug**
Influxdb_client 2.0.0 running on web (Chrome debug) against a local influx 1.8.5 OSS instance throws the following error:

```
Error: Unsupported operation: String.fromEnvironment can only be used as a const constructor
    at Object.throw_ [as throw] (http://localhost:64108/dart_sdk.js:5061:11)
    at Function.fromEnvironment (http://localhost:64108/dart_sdk.js:44051:17)
at new api$.InfluxDBClient.new (http://localhost:64108/packages/influxdb_client/api.dart.lib.js:17429:58)
```

Based on the following comment I found on the web, I believe the error to be somewhere in the client code: 
_This is because browsers do not have access to system environment properties. fromEnvironment constructor can only be accessed during compilation and therefore they are constant as far as Dart code is concerned._

**To Reproduce**
1. Try to connect the influx client against a 1.8 influx instance using in a web env.

**Expected behavior**
The operation to be supported

**Specifications:**
 - Client Version: 2.0.0
 - InfluxDB Version: 1.8.5 OSS
 - Platform: Flutter (Chrome)

**Additional context**
I have not tested this against an Influx 2.0 instance. So I cannot tell whether this is a downward compatibility issue.

Many thanks for looking into this!

**Comment by bednar** [comment]
Hi @BSBoatia,

thanks for using our client.

I have prepared a fixed version within #27.

If you would like to use the fixed version of the client before release into pub.dev, then you can import the library by:

```
dependencies:
  influxdb_client:
    git:
      url: git@github.com:influxdata/influxdb-client-dart.git
      ref: fix/browser-compatibility

```

https://dart.dev/tools/pub/dependencies#git-packages
Regards
