### ISSUE TITLE
aggregateWindow() resulting in InfluxDBException: statusCode = 500, code = null, message = null

### ISSUE THREAD

**Issue by BSBoatia** [influxdata/influxdb-client-dart#28]
Hello,

I'm using the latest client #26 (merged into master) and are running into the following issue with Influx 1.8.5. The query is working fine against our managed influxdb cloud instance, thus I assume it's somehow related to the client or 1.8.5. It would be great if you could have a look at the issue.

**Describe the bug**
Using `aggregateWindow()` in a flux query result in an exception against InfluxDB 1.8.5 OSS using the latest Flutter client #26 (merged into master) -- `InfluxDBException: statusCode = 500, code = null, message = null`

**To Reproduce**
Run a query using aggregateWindow() against a 1.8.5 instance.

**Expected behavior**
The query to return aggregated results.

**Specifications:**
 - Client Version: influxdb_client (master branch at time of posting with #26 merged)
 - InfluxDB Version: 1.8.5 OSS
 - Platform: Flutter (running client on iOS)

**Additional context**
The query works 
- fine on managed InfluxData cloud
- on the local 1.8.5 if we delete aggregatedWindow()

The following code produces the exception:
```
      InfluxDBClient influxClient = InfluxDbService().client;
      QueryService queryService = influxClient.getQueryService();

      String fluxQuery = '''
        from(bucket: "my-bucket")
          |> range(start: -5m)
          |> filter(fn: (r) => r["_measurement"] == "pi_sensors")
          |> filter(fn: (r) => r["_field"] == "cpu_usage")
          |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
          |> yield(name: "mean")
      ''';

      Stream<FluxRecord> recordStream = await queryService.query(fluxQuery);
      await recordStream.forEach((record) {
        // DO SOMETING
      });
```

and the output from debug
```
flutter: >> POST http://10.10.10.1:8086/api/v2/query?org =====
flutter: >> headers: {Accept-Encoding: gzip, Content-Type: application/json; charset=utf-8, Authorization: Token data_extractor:sk2RV5XuQjjtEZJj, User-Agent: influxdb-client-dart/2.1.0-dev}
flutter: >> contentLength: 499
flutter: << status: 500 - contentLength: null
flutter: << headers: {transfer-encoding: chunked, date: Wed, 05 Jan 2022 18:47:39 GMT, x-influxdb-version: 1.8.5, content-type: text/csv; charset=utf-8, x-influxdb-error: panic: runtime error: invalid memory address or nil pointer dereference, request-id: f4dcdfc5-6e57-11ec-b7c6-0242ac120007, x-influxdb-build: OSS, x-request-id: f4dcdfc5-6e57-11ec-b7c6-0242ac120007}
flutter: InfluxDBException: statusCode = 500, code = null, message = null
flutter: << status: 500 - contentLength: null
flutter: << headers: {transfer-encoding: chunked, date: Wed, 05 Jan 2022 18:47:39 GMT, x-influxdb-version: 1.8.5, content-type: text/csv; charset=utf-8, x-influxdb-error: panic: runtime error: invalid memory address or nil pointer dereference, request-id: f4dc65ce-6e57-11ec-b7c5-0242ac120007, x-influxdb-build: OSS, x-request-id: f4dc65ce-6e57-11ec-b7c5-0242ac120007}
flutter: InfluxDBException: statusCode = 500, code = null, message = null
```
Thanks a lot!

**Comment by bednar** [comment]
Hi @BSBoatia,

the HTTP error code `500` means server side error. 

The reason is mention in `x-influxdb-error` header:

> x-influxdb-error: panic: runtime error: invalid memory address or nil pointer dereference

Regards

**Comment by BSBoatia** [comment]
Hi @bednar thanks for looking into this. 
I can understand why you closed the issue but don’t understand  the error message / have any idea what to with that.
The error occurs if I add the aggregate function. The query without aggregate works just fine.
Also, we have the structure mirrored in influx cloud and the query is working via the data explorer.
Do you have any idea what Could cause the null pointer. I assumed that part of the aggregation function is passed correctly.

Thanks!

**Comment by bednar** [comment]
Hi @BSBoatia, 

>  don’t understand the error message / have any idea what to with that.

Unfortunately I don't, it's a server thing. Try upgrading InfluxDB to 1.8.0 or ask in our Slack channel - https://www.influxdata.com/slack

Regards

**Comment by BSBoatia** [comment]
Hi @bednar.

this is indeed a server issue. mean(), as well as other aggregateWindow() functions are not supported on a 32bit ARM system.

This thread was actually really helpful, in case someone else stumbles into the same issue here: https://github.com/influxdata/flux/issues/2505

**Comment by bednar** [comment]
@BSBoatia thanks for detail information
