### ISSUE TITLE
Change package example structure to respect pub.dev guidelines

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-dart#29]
![image](https://user-images.githubusercontent.com/455137/149728810-fd2dc4e5-5668-459b-b8b1-8e55afff2724.png)

- https://pub.dev/packages/influxdb_client/score
- https://dart.dev/tools/pub/package-layout#examples

**Comment by rhajek** [comment]
There are also outdated dependencies:
![image](https://user-images.githubusercontent.com/2169548/149773620-ebc97f72-5ddc-4cf5-89c3-794035975836.png)
