### ISSUE TITLE
SocketExceptions while writing

### ISSUE THREAD

**Issue by Pali15** [influxdata/influxdb-client-dart#39]
Every time I'm trying to write I'll get
 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: The remote computer rejected the connection request.
 (OS Error: The remote computer rejected the connection request.
, errno = 1225), address = localhost, port = 58700

Reproduce
![image](https://user-images.githubusercontent.com/75538899/158150754-f24d3991-1cb8-47dd-bc1a-339faf60f7a3.png)

 - InfluxDB Version: 2.2.0
 - Platform: Flutter Debug mode in windows

**Comment by bednar** [comment]
Hi @Pali15,

thanks for using our client.

It looks like your `url` of InfluxDB is not correct. The `http://localhost:8080` is a url of your simulator. You have to use the IP of your computer.

Regards

**Comment by bednar** [comment]
It looks like problem in your network configuration. Maybe it is caused by firewall/antivirus... Are you able to login into InfluxDB from browser (http://98.207.254.136:8086)?

**Comment by Pali15** [comment]
No I am not able to do that. It is probably my firewall. Can you tell me which application should I enable on my firewall or antivirus?

**Comment by bednar** [comment]
> Can you tell me which application should I enable on my firewall or antivirus?

Unfortunately I don't use Windows OS 😞

**Comment by Pali15** [comment]
I think the problem is not my firewall. Is it possible that the client is not online? 
![image](https://user-images.githubusercontent.com/75538899/158561471-f52ce595-0983-47a4-8ad3-045ccdc8a467.png)
![image](https://user-images.githubusercontent.com/75538899/158563781-9f01ffef-deb6-499f-b4f7-2bd10c3612cc.png)

**Comment by bednar** [comment]
The `getPing()` is the best way to determine successful connection to InfluxDB.
