### ISSUE TITLE
Web - "Error: XMLHttpRequest error"

### ISSUE THREAD

**Issue by catteneo** [influxdata/influxdb-client-dart#47]
**Describe the bug**
I'm having an issue when querying an influxdb server on an app running on web (either chrome or edge).
When I query the server I get this error:

`Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 963:28                get current
packages/http/src/browser_client.dart 69:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1685:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 557:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1530:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37309:58                              <fn>`

Same code works without problem on Android and Windows.

**To Reproduce**
1. init client
2. get query service
3. query server

**Specifications:**
 - Client Version: 2.3.0
 - InfluxDB Version: 1.8
 - Platform: Web

**Comment by sranka** [comment]
You have to inspect the developer console (F12) and observe the networking to see the root cause of `XMLHttpRequest error`. It might have the same root cause as in https://stackoverflow.com/questions/64458696/in-flutter-web-getting-xmlhttprequest-error-while-making-http-call.

**Comment by catteneo** [comment]
> You have to inspect the developer console (F12) and observe the networking to see the root cause of `XMLHttpRequest error`. It might have the same root cause as in https://stackoverflow.com/questions/64458696/in-flutter-web-getting-xmlhttprequest-error-while-making-http-call.

Found it:
`
Access to XMLHttpRequest at 'http://192.168.1.104:8086/api/v2/query?org=my-org' from origin 'http://localhost:55913' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

Any way to add headers to the request? Couldn't find it..

**Comment by catteneo** [comment]
@sranka fount this issue opened by you [https://github.com/influxdata/influxdb/issues/19715](url)

Seems to be what I am facing.
I am running Influx on an RPi 32bit, running version 1.8.10
And this was not fixed for this version if I got the flow correctly.

**Comment by sranka** [comment]
If you are using RPI 3 or newer, you might consider switching to a 64bit OS and then use the newest InfluxDB v2 that supports CORS properly. You can also incorporate a proxy to fix CORS issues, or you could use a custom build of InfluxDB v1 with CORS fixed. 

There is nothing we could do in the dart client to resolve this issue, you have to find/use another solution or workaround on the server side.
