### ISSUE TITLE
 InfluxDB 1.8 compatibility

### ISSUE THREAD

**Issue by JohanScheepers** [influxdata/influxdb-client-dart#68]
The documentation state compatible with InfluxDB 1.8, where in 1.8 do you find org and buckets?

`InfluxDB 1.8 API compatibility
  var client = InfluxDBClient(
    url: 'http://localhost:8086',
    username: '...',
    password: '...',
    org: 'my-org',
    bucket: 'my-bucket',
    debug: true);`

**Comment by bednar** [comment]
Hi @JohanScheepers,

thanks for using our client.

The documentation is not correct... you can use following code to connect into `1.8`:

```dart
var database = 'mydb';
var retentionPolicy = 'autogen';
var client = InfluxDBClient(
  url: 'http://localhost:8086',
  bucket: '$database/$retentionPolicy',
  username: 'my-username',
  password: 'my-password'
);
```
